apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: django-flux-auth
  newTag: 3b25608f196b9ddab0ffc6b2b9751ffe04454250
