apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: django-flux-auth
  newName: django-flux-auth
  newTag: 52121d3ce39d7cfb688a84d8242cf84ae6fc9f64
