apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: flux-app-demo
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: flux-app-demo
    tier: backend