apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: django-flux-shop
  newName: django-flux-shop
  newTag: 6c7c6c94b7e0cd4663b5078e68e55acf9b28bdb3
