name: Dockerize Microservices
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # -
      #   name: Publish auth micorservice to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: services/auth_service
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/flux-django-auth, latest, ${{ github.run_number}}
      -
        name: Publish Image to DockerHub
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          BASE_NAME="$USERNAME/django-flux-auth"
          IMAGE_NAME="$BASE_NAME:$GITHUB_SHA"
          docker pull $BASE_NAME || true
          docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f services/auth_service/Dockerfile .
          docker push $IMAGE_NAME
          docker push $BASE_NAME
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}