name: Release Flux-DJANGO-MS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dockerize MS services
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build and push
    - name: Publish auth service to Registry
      uses: docker/build-push-action@v1
      with:
        repository: jayefee/django-flux-auth
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: services/auth_service
    
    - name: Publish shop service to Registry
      uses: docker/build-push-action@v1
      with:
        repository: jayefee/django-flux-shop
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: services/shop_service

  deploy:
    name: update and push images
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize for auth
      working-directory: services/auth_service/kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update auth yamls
      working-directory: services/auth_service/kustomize
      run: |-
        ./kustomize edit set image IMAGE_PLACEHOLDER=django-flux-auth:${{ github.sha }}
    
    - name: Set up Kustomize for shop
      working-directory: services/shop_service/kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Update shop yamls
      working-directory: services/shop_service/kustomize
      run: |-
        ./kustomize edit set image IMAGE_PLACEHOLDER=django-flux-shop:${{ github.sha }}

    # Commit and push
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

# name: cd
# on:
#   push:
#     branches:
#       - main
# jobs:
#   docker:
#     name: Dockerize Microservices
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Publish flux-auth Image to DockerHub
#         run: |
#           cd $GITHUB_WORKSPACE
#           echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
#           BASE_NAME="$USERNAME/django-flux-auth"
#           IMAGE_NAME="$BASE_NAME:$GITHUB_SHA"
#           docker pull $BASE_NAME || true
#           docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f services/auth_service/Dockerfile services/auth_service/
#           docker push $IMAGE_NAME
#           docker push $BASE_NAME
#         env:
#           USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
#       - name: Publish flux-shop Image to DockerHub
#         run: |
#           cd $GITHUB_WORKSPACE
#           echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
#           BASE_NAME="$USERNAME/django-flux-shop"
#           IMAGE_NAME="$BASE_NAME:$GITHUB_SHA"
#           docker pull $BASE_NAME || true
#           docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f services/shop_service/Dockerfile services/shop_service/
#           docker push $IMAGE_NAME
#           docker push $BASE_NAME
#         env:
#           USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     needs: docker

#     steps:
#     - name: Check out code
#       uses: actions/checkout@v2

#     - name: Setup Kustomize
#       uses: imranismail/setup-kustomize@v1
#       with:
#         kustomize-version: "3.6.1"

#     - name: Update Auth Service Kubernetes resources
      
#       run: |
#        cd services/auth_service/kustomize
#        kustomize edit set image django-flux-auth=django-flux-auth:$GITHUB_SHA
#        cat kustomization.yaml
#        cd ../../shop_service/kustomize
#        kustomize edit set image django-flux-shop=django-flux-shop:$GITHUB_SHA
#        cat kustomization.yaml
        
#     - name: Commit files
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git commit -am "Bump docker tag"
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: ${{ github.ref }}