name: Dockerize Microservices
on: push
jobs:
  build-container:
    name: Build Docker contaienr Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish auth micorservice to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
          repository: jayefee/flux-django-auth
          path: services/auth_service
          tags: latest, ${{ github.run_number}}